const ADD_DEVICE = 'ADD_DEVICE';
const SERVER_SEND_STATUS = 'SERVER_SEND_STATUS';
const CLIENT_CONNECT_SERVER = 'CLIENT_CONNECT_SERVER';

export {ADD_DEVICE, SERVER_SEND_STATUS, CLIENT_CONNECT_SERVER};
