const ADD_DEVICE = 'ADD_DEVICE';
const SERVER_SEND_STATUS = 'SERVER_SEND_STATUS';
const CLIENT_CONNECT_SERVER = 'CLIENT_CONNECT_SERVER';
const CLIENT_SEND_ORDER = 'CLIENT_SEND_ORDER';

export {
  ADD_DEVICE,
  SERVER_SEND_STATUS,
  CLIENT_CONNECT_SERVER,
  CLIENT_SEND_ORDER,
};
